= Example project for use cases of jQAssistant

This is a synthetic Java and Maven project to demonstrate some applications of jQAssistant.

== Structure of the example project

The project contains the following Maven projects:

1. `report` in the directory `report` contains the rules plugin for jQAssistant.
2. `example-project` is a Maven Java project which uses the rules plugin to detect violations of the hexagonal architecture.

== How to run the example

The example below shows how to build the example project and to generate the report.

[source,shell]
----
$ cd jqa-example-project-for-thales-consulting/example-project
$ mvn -f report/ clean install
$ mvn -f example-project/ clean install
----

The generated report can be found in the directory `target/jqassistant/report/asciidoc/`.

== How to run the Neo4J Browser

To run the Neo4J Browser, you must execute the following command.

[source,shell]
----
$ cd example-project
$ mvn \
    -Djqassistant.store.directory=target/jqassistant/store com.buschmais.jqassistant:jqassistant-maven-plugin:$(mvn -q -DforceStdout -Dexpression=jqassistant-plugin.version help:evaluate):server
----

During the startup of the server, the address of the server is logged to the console.
