openapi: 3.1.0
info:
  title: allOf Example
  version: 0.2.3


paths:
  /oneofresources:
    put:
      operationId: updateResource
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    firstname:
                      type: string
                - type: object
                  properties:
                    lastname:
                      type: string

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                # Zur Bedeutung von OneOf siehe die OpenAPI Spezifikation unter
                # Kapitel 4.8.24 Schema Object
                # https://spec.openapis.org/oas/v3.1.0#schema-object

                # Ein Objekt muss genau einem Schema aufgeführten Schemas entsprechen
                oneOf:
                  # Schema 1
                  - type: object
                    properties:
                      firstname:
                        type: string
                  # Schema 2
                  - type: object
                    properties:
                      secondname:
                        type: string
                  # Schema 3
                  - type: object
                    properties:
                      lastname:
                        type: string
                      title:
                        type: string
